### ISSUE TITLE
Onboarding document does not match the Cisco site

### ISSUE THREAD

**Issue by hvdkooij** [automateyournetwork/Cisco_API_v2#1]
The onboarding document does not mtach my experience with the Cisco websites.
 1. There is no option to add a developer API role to the account. But this might also be the case when someone has done this on your account in the past. Not sure how I could find out why.
 2. The enrollement on the Cisco API website is extremely confusing to me and does not match my experience with the website.

To be honest I don't understand the site well enough to write a better document.

**Comment by automateyournetwork** [comment]
Sorry to hear that I've tried to document the Total Care API site and enrollment best I can - maybe open an issue with your cisco support team or account rep to help you get your API keys?

**Comment by hvdkooij** [comment]
Well. it seems the process seems to be rather unlike  the documentation.
Such is the fate of documents I guess. It's hard to keep up with changes
